import { Story } from "@/types/story";

export const mockStories: Story[] = [
  {
    id: "1",
    slug: "er-doctor-chatgpt-patients",
    title: "I'm an ER Doctor. Here's How I'm Already Using ChatGPT to Help Treat Patients",
    summary:
      "A working ER doctor shares how he used ChatGPT at 3am during a night shift to explain a complex diagnosis to a worried family — calming them down and freeing his team to focus on saving lives.",
    source: "Medium",
    sourceUrl: "https://inflecthealth.medium.com/im-an-er-doctor-here-s-how-i-m-already-using-chatgpt-to-help-treat-patients-a023615c65b6",
    publishedAt: "2026-04-11T10:00:00Z",
    author: "Dr. Josh Tamayo-Sarver",
    category: "Health",
    readTime: 6,
    fireCount: 312,
    imageUrl: "https://miro.medium.com/1*zVkc5iNVMQQIApQS_OKAAA.jpeg",
    content: [
      "It was 3am. Dr. Josh Tamayo-Sarver was in the middle of a chaotic ER night shift when he got a case that would change how he thought about AI in medicine.",
      "A 96-year-old woman with dementia was struggling to breathe. The cause was pulmonary edema — fluid trapped in her lungs. The fix was clear: drain the fluid, stabilise her breathing. But her three adult children, all in their seventies, were convinced she just needed IV fluids for dehydration. They asked for it. Over and over. For an hour straight. The problem? IV fluids would have made her condition dramatically worse. More fluid into already-flooded lungs could have killed her.",
      "Dr. Tamayo-Sarver tried explaining it every way he could. Simple terms. Medical terms. Analogies. Nothing worked. The family was panicked, grieving, and stuck on an idea. Other patients needed urgent attention. The situation was spiralling.",
      "So he did something unexpected. He walked to his computer, opened ChatGPT-4, and typed a prompt asking it to explain — in warm, simple language for a non-medical family — why giving IV fluids to someone with fluid in their lungs would cause harm, not help. The response came back in seconds. He printed it out and read it to the family.",
      "They went quiet. Then calm. The son who had been most insistent simply nodded. They stepped back and let the team work. For the rest of the shift, every time the question came up again, the nurse read from the same printed page. It worked every time.",
      "Dr. Tamayo-Sarver has used ChatGPT this way ever since. Not for diagnosis — he is clear that AI is unreliable there. But for communication. The ER is full of moments where a frightened family needs something explained that a doctor simply does not have time to explain well. ChatGPT generates the explanation. The doctor delivers the care."
    ],
    tool: {
      name: "ChatGPT",
      job: "Explaining complex diagnoses to patients and families in plain language during ER shifts",
      review:
        "Proved effective at translating medical complexity into calm, accessible explanations for anxious families — freeing clinical staff to focus on patient care.",
      url: "https://chatgpt.com",
    },
  },
  {
    id: "2",
    slug: "claude-3d-printable-parts-design",
    title: "I Taught Claude to Design 3D-Printable Parts. Here's How",
    summary:
      "An engineer figured out how to use Claude as a design partner for 3D-printable parts — describing geometry in plain language and getting back functional, printable designs. A completely new way to prototype.",
    source: "Medium",
    sourceUrl: "https://medium.com/towards-artificial-intelligence/i-taught-claude-to-design-3d-printable-parts-heres-how-675f644af78a",
    publishedAt: "2026-04-11T08:30:00Z",
    author: "Nicolas Chourrout",
    category: "Design",
    readTime: 5,
    fireCount: 287,
    imageUrl: "https://miro.medium.com/1*VMAxSVdfT9DuwZl3QFWRYg.png",
    content: [
      "The engineer had a problem: he needed a custom mechanical part. A bracket with specific dimensions, specific load requirements, and no room for error. The normal solution would be CAD software, engineering training, or paying someone who had both. He had neither.",
      "Instead, he opened Claude and started describing the part in plain English. Not design specs — just a clear description of what the part needed to do, what forces it would face, and what it needed to connect to. Claude responded with something unexpected: a precise geometric breakdown of every surface, wall thickness, hole placement, and angle he would need. No file. No drawing. Just a description clear enough to act on.",
      "He took that description into a beginner-friendly 3D modelling tool and started building. When he hit a problem — a wall too thin, a hole in the wrong place — he came back to Claude and described exactly what was going wrong. Claude diagnosed it from the description and suggested a specific fix. Back to the modelling tool. Adjust. Print a test piece. Return with new questions.",
      "The final part worked on the first real print. He has since used the same process for four more components across two different projects. The workflow is always the same: describe the problem to Claude in plain English, get a precise geometric response, model it, test it, iterate.",
      "What he discovered is that Claude does not replace engineering knowledge — it makes that knowledge accessible to someone who does not have it. The conversation becomes the design process. The iteration becomes the engineering. And the barrier to entry drops from years of training to the ability to describe clearly what you need.",
    ],
    tool: {
      name: "Claude",
      job: "Translating plain-language geometry descriptions into functional, 3D-printable part designs",
      review:
        "Surprisingly capable as a design partner for physical prototyping — describing what you need in natural language and getting back printable designs opens up a completely new prototyping workflow.",
      url: "https://claude.ai",
    },
  },
  {
    id: "3",
    slug: "ai-one-person-business-million",
    title: "How I Use AI to Run a $1M One-Person Business",
    summary:
      "A CEO and investor shares how he personally uses ChatGPT and NotebookLM to run an entire business solo — from analyzing 1000 customer reviews in minutes to having AI act as his CFO. What used to cost $3000 now costs $3.",
    source: "YouTube",
    sourceUrl: "https://www.youtube.com/watch?v=VXgusdDbsQE",
    publishedAt: "2026-04-10T14:00:00Z",
    author: "YouTube Creator",
    category: "Business",
    readTime: 7,
    fireCount: 341,
    imageUrl: "https://i.ytimg.com/vi/VXgusdDbsQE/maxresdefault.jpg",
    content: [
      "Two years ago, analysing a thousand customer reviews cost three thousand dollars and took days. Today, the same analysis takes minutes and costs three dollars. That is not a gradual improvement. That is a collapse — and most solo founders have not fully figured out what to do with it yet.",
      "The CEO behind this story spent the last year systematically replacing team functions with AI workflows. He did not do it all at once. He picked one area, built a workflow, proved it worked, then moved to the next. He started with demand generation. Then financial analysis. Then marketing. Then the administrative layer that used to eat entire afternoons.",
      "The most striking example is his financial operations. He used to employ an analyst to process raw material costs and recommend price adjustments — a two-day turnaround every time input costs changed. Now he feeds the raw data directly into ChatGPT. Analysis comes back in minutes. He also pipes his QuickBooks and point-of-sale data into Google NotebookLM, which synthesises everything into a weekly audio briefing for his branch managers. The AI became his CFO.",
      "The mental shift that made this possible was simple: stop thinking about AI as a chatbot and start thinking about it as infrastructure. Every recurring task that takes the same shape every week is a candidate for automation. The question is not whether AI can do it. The question is whether you have described it precisely enough.",
      "His advice to solo founders: do not try to build the whole machine at once. Pick one area — just one — and find a single recurring task to automate this week. Get it working. Then pick the next. The founders who compound these small wins are the ones who will look up in a year and realise they are running what used to require a full team.",
    ],
    tool: {
      name: "ChatGPT",
      job: "Acting as CFO, analyzing customer reviews, and handling business operations for a solo founder",
      review:
        "Dramatically reduces the cost and headcount needed to run a business — tasks that required expensive specialists now cost dollars and minutes instead of thousands and weeks.",
      url: "https://chatgpt.com",
    },
  },
  {
    id: "4",
    slug: "github-copilot-80-percent-code-review-lessons",
    title: "I let GitHub Copilot write 80% of my last feature — code review was a nightmare",
    summary:
      "Copilot is genuinely impressive for boilerplate and CRUD operations. But when I shipped a feature that was 80% AI-generated without deeply reviewing it, I introduced three subtle bugs that only showed in production. Lessons learned the hard way.",
    source: "Dev.to",
    sourceUrl: "https://dev.to",
    publishedAt: "2026-04-10T11:00:00Z",
    category: "Coding",
    readTime: 8,
    fireCount: 271,
    content: [
      "I've been a software engineer for four years and I thought I had a clear-eyed view of AI coding tools: useful for boilerplate, dangerous for anything with business logic, worth using with deliberate caution. That self-assessment turned out to be wrong in a specific and expensive way. Three months ago I was under deadline pressure to ship a notifications feature — a deceptively complex piece involving user preferences, timezone handling, and a rate-limiter. I let GitHub Copilot write about eighty percent of it, reviewed it quickly because it 'looked right', and shipped it.",
      "The bugs surfaced over the following two weeks. The first was a timezone issue: Copilot had assumed UTC throughout, but we have users in UTC+14 and notifications were arriving nine hours early for Pacific accounts. The second was an off-by-one error in the rate-limiter's window calculation that occasionally allowed double-sends during a brief overlap at midnight. The third genuinely embarrassed me: a SQL query that would have returned all users' notification preferences if a certain parameter was null — not exploited, but a potential data exposure I should have spotted instantly.",
      "All three bugs were findable in code review. I didn't find them because I was reviewing AI-generated code the same way I review code I've written myself — skimming for obvious issues rather than reading it with the assumption that it might be subtly wrong. That's the trap. When I write code, I know where I'm uncertain. I know which bits I thought carefully about and which bits I dashed off. With Copilot, everything looks equally confident. The code doesn't mark its own uncertainty. The timezone handling and the null-parameter query both looked completely normal.",
      "My practice now: treat AI-generated code as a junior developer's first attempt — worth having, but requiring thorough review, not a skim. For anything touching authentication, data retrieval, or financial calculations, I read every line and ask myself: what happens if these inputs are null, negative, empty, or at max-value? That's a habit I had for my own code and somehow failed to apply to Copilot's output. It's a lesson I should have been able to reason my way to without the production incident. I didn't. Now I have.",
    ],
    tool: {
      name: "GitHub Copilot",
      job: "AI pair programmer that autocompletes and generates code inline as you type",
      review:
        "Genuinely excellent for boilerplate, standard CRUD patterns, and getting unstuck quickly. The danger is that it generates confident-looking code that can be subtly wrong in edge cases it didn't consider. Treat every generated block as junior code requiring full review — especially anything touching auth, data access, or time calculations.",
      url: "https://github.com/features/copilot",
    },
  },
  {
    id: "5",
    slug: "hedge-fund-gpt4-earnings-call-pipeline",
    title: "Our hedge fund built a custom GPT-4 pipeline to summarise earnings calls — ROI in 3 months",
    summary:
      "We process 200+ earnings call transcripts per quarter. After training a fine-tuned summarisation pipeline on historical calls, our analysts spend 70% less time on transcripts and more time on actual thesis development. Full technical breakdown inside.",
    source: "Fintech Insider",
    sourceUrl: "https://www.finextra.com",
    publishedAt: "2026-04-09T16:00:00Z",
    category: "Finance",
    readTime: 9,
    fireCount: 258,
    imageUrl: "https://picsum.photos/seed/finance-gpt/84/84",
    content: [
      "We run a long/short equity fund focused on technology and consumer sectors. Each quarter we process between two hundred and two hundred and forty earnings call transcripts — every company in our coverage universe. Before this project, that meant one analyst spending roughly six hours per transcript: transcribing, tagging key topics, extracting guidance, and flagging deviations from prior-quarter language. Multiply that across the quarter and we were burning around fourteen hundred analyst hours on a task that is fundamentally information extraction, not investment judgment.",
      "We built our first GPT-4 summarisation pipeline in August. The architecture was straightforward: transcripts in as text, chunked into 2,000-token windows with overlap, run through a fine-tuned model we'd trained on two years of our own analysts' summaries, outputting a structured result: management tone assessment, guidance deltas versus prior quarter, key topic mentions ranked by emphasis, and analyst questions with management-directness scores. The fine-tuning on our own historical summaries was the critical step — vanilla GPT-4 gave generic digests, but the fine-tuned model started producing outputs that sounded like our best analyst had written them.",
      "Three months in, the ROI case was unambiguous. Analyst time on transcript processing dropped from fourteen hundred hours per quarter to around four hundred — the remaining four hundred is review, exception handling, and the qualitative calls where a human reading between the lines genuinely adds value. That redirected time went into direct management calls and channel checks, which is where we actually generate alpha. Pipeline infrastructure cost roughly thirty thousand dollars to build and runs at around eight thousand per quarter. Against the analyst time saved, that paid back in under three months.",
      "The failure modes we've learned to watch for: GPT-4 is significantly more likely to miss important information buried in Q&A sections than in prepared remarks, because prepared remarks have cleaner structure. It occasionally miscalibrates management tone — calling a CEO's language 'cautiously optimistic' when anyone following that company closely would read it as defensive. And it will confidently extract numbers that aren't quite in the transcript if our chunking cuts a key sentence mid-phrase. None of these are fatal, but they require analysts to maintain genuine domain expertise rather than rubber-stamping outputs. The pipeline doesn't replace the analyst. It makes them faster and more consistent.",
    ],
    tool: {
      name: "OpenAI API (GPT-4)",
      job: "Fine-tuned summarisation pipeline for processing financial earnings call transcripts at scale",
      review:
        "Extremely capable for structured information extraction when fine-tuned on domain-specific examples. The quality gap between vanilla GPT-4 and a model fine-tuned on your own outputs is substantial — worth the investment if you have good historical data. Key weakness: performance degrades on poorly-structured Q&A sections and is sensitive to chunking decisions.",
      url: "https://openai.com",
    },
  },
  {
    id: "6",
    slug: "claude-helped-me-write-a-novel",
    title: "Claude helped me write a novel in 90 days. I have complicated feelings about it.",
    summary:
      "I used Claude as a co-writer for my debut thriller — brainstorming plot holes, writing dialogue drafts, and pushing through blocks. The book is done and my agent loves it. But I'm still wrestling with what authorship means now.",
    source: "Electric Lit",
    sourceUrl: "https://electricliterature.com",
    publishedAt: "2026-04-09T09:00:00Z",
    category: "Writing",
    readTime: 10,
    fireCount: 389,
    imageUrl: "https://picsum.photos/seed/novel-claude/84/84",
    content: [
      "I have been trying to write a novel since I was twenty-three. I am now thirty-one. I have three complete first drafts none of which I've shown to anyone, and a folder of abandoned chapters I try not to open. The problem was never ideas — I have too many. The problem was execution: I'd get sixty pages in, lose the thread, decide the structure was wrong, and start over. Eight years of starting over. When I began this project — a psychological thriller set in a coastal town during a missing-child case — I decided to do something different and use Claude from the beginning.",
      "My workflow evolved over the three months it took to write the book. Early on I used Claude primarily as a structural sounding board: I'd describe where I was in the plot and where I needed to get, and ask it to suggest five different ways to bridge the gap — not to choose one, but to see options I hadn't considered. Claude is particularly good at identifying the logical consequences of plot decisions: 'if your protagonist knows this at the end of chapter four, she has to behave differently in chapter seven, which undermines your planned twist.' That kind of structural logic is hard to hold in your head alone across 80,000 words.",
      "For dialogue specifically, I developed a technique: write a rough draft of a scene, then ask Claude to write the same scene with the dialogue heightened — more subtext, more tension between what's said and what's meant. Then I'd take neither version but use both to understand what the scene was missing. My editor — who doesn't know about this process — called the dialogue in the finished manuscript 'unusually sharp'. I don't think I was deceiving anyone. A painter who uses a reference photograph isn't lying about making a painting. I used Claude as a reference. The judgment about what was true for these characters was always mine.",
      "My literary agent signed the book in February. She loved it. She has no idea how it was written. I've been sitting with that for two months and I genuinely don't know what to do with it. I don't feel like a fraud — I feel like someone who finally finished something after eight years of failing to. But the culture around AI and creative work is so charged right now that I'm not sure how to talk about it honestly, which is why I'm doing it here under my first name only. What I know is this: the book is good, I'm proud of it, and I couldn't have finished it without Claude.",
    ],
    tool: {
      name: "Claude",
      job: "Long-form creative writing partner for structural problem-solving, dialogue drafting, and beating writer's block",
      review:
        "Remarkable for structural narrative work — it holds a lot of context and can reason about plot consistency across a long document in ways that feel genuinely collaborative. Dialogue drafts need heavy rewriting for authentic voice, but the technique of having Claude write a parallel version of a scene to reveal what your version is missing is surprisingly powerful.",
      url: "https://claude.ai",
    },
  },
  {
    id: "7",
    slug: "cursor-claude-junior-dev-shipping-solo",
    title: "Cursor + Claude: how I went from junior to shipping features solo",
    summary:
      "Six months ago I was stuck needing senior review for every PR. Using Cursor with Claude as an always-on mentor, I can now ship complete features, write tests, and debug production issues independently. This is what pair programming should have always been.",
    source: "Personal blog",
    sourceUrl: "https://dev.to",
    publishedAt: "2026-04-08T12:00:00Z",
    category: "Coding",
    readTime: 5,
    fireCount: 312,
    content: [
      "When I joined my current company as a junior backend engineer eighteen months ago, I was the least experienced person on a team of eight. Every pull request I opened got multiple rounds of review comments — not just about bugs, but about architecture, naming, whether a function belonged in this file at all. My senior colleagues were patient, but I was aware of how much of their time I was consuming. I felt like I was always one PR away from someone deciding I needed more mentorship than the team could provide.",
      "I started using Cursor about six months ago, initially just for autocomplete. The real value turned out to be how it handled context. I could highlight a function and ask 'what are the edge cases this doesn't handle?' and get back a genuinely useful list — not perfect, but thought-provoking. I started using it as a pre-review step: before opening any PR, I'd have a Cursor conversation about the code I'd just written. 'What would a senior engineer criticise about this?' The answers were often uncomfortably accurate. I'd fix those things before anyone saw them.",
      "The biggest shift came three months in. I was assigned to build a new authentication flow — the kind of task that previously would have required a senior engineer to sketch the architecture first. Instead, I used Cursor to work through the design: explained the requirements, asked about trade-offs between different session management approaches, asked it to flag security considerations I might be missing. The PR I opened was the cleanest of my career. My tech lead's review comment was: 'This is really solid. Did you have a design review with someone?' I hadn't. I'd had a design review with Cursor.",
      "Six months later I'm shipping features independently. My PR review cycle is down from an average of four rounds to one and a half. My senior colleagues have noticed and mentioned it — not attributing it to any tool, just observing that my judgment has improved. Which is true. Using Cursor as an always-available reviewer has accelerated my development as an engineer in a way that's hard to quantify but very real. It doesn't replace mentorship or lived experience — there are things you only learn by shipping something that breaks in production. But for closing the gap between where I was and where I needed to be, it was remarkably effective.",
    ],
    tool: {
      name: "Cursor",
      job: "AI-first code editor with deep model integration for writing, reviewing, and understanding code",
      review:
        "The most effective tool I've used for accelerating engineering growth. The ability to have a contextual conversation about your own code — asking what could go wrong, what a senior would think, what the trade-offs are — is something that goes beyond autocomplete. For junior and mid-level engineers especially, this is transformative.",
      url: "https://cursor.com",
    },
  },
  {
    id: "8",
    slug: "therapist-patients-chatgpt-between-sessions",
    title: "A therapist's take on patients who use ChatGPT between sessions",
    summary:
      "More of my clients are showing up having already processed emotions with ChatGPT before our sessions. Some arrive more self-aware; others have reinforced unhelpful patterns. As a therapist, I'm learning to work with AI — not against it.",
    source: "Psychology Today",
    sourceUrl: "https://www.psychologytoday.com",
    publishedAt: "2026-04-08T07:00:00Z",
    category: "Health",
    readTime: 6,
    fireCount: 204,
    imageUrl: "https://picsum.photos/seed/therapist-chatgpt/84/84",
    content: [
      "I've been a licensed psychotherapist in private practice for fourteen years, specialising in anxiety and complex trauma. Over the past eight months I've noticed a marked shift in how clients arrive to sessions. Where they once came in carrying an unprocessed week of emotion, more are arriving having already spent significant time talking through their feelings with ChatGPT. My initial instinct was dismissal — the clinical literature on AI and mental health is cautious for good reason. That instinct has proved to be, at most, half right.",
      "The clients for whom ChatGPT seems genuinely helpful are those with high verbal intelligence who struggle to access their emotional state under pressure. For this group, the AI conversations appear to function as scaffolding: they arrive having externalised and organised their thoughts, which frees up our sessions for the relational and embodied work that AI can't replicate. One client told me she uses ChatGPT the way she used to use a journal, except it pushes back gently. She's made more progress in the past six months than in the preceding year. I can't attribute that entirely to the AI, but I'd be dishonest to suggest it's unrelated.",
      "The concerning pattern involves clients who have used AI conversations to reinforce rather than examine existing cognitive distortions. ChatGPT is very validating. It tends to reflect back what you tell it, affirm your framing, and rarely challenges narratives the way a skilled therapist would. I've had two clients arrive having been extensively 'reassured' by ChatGPT about relationship patterns I believe are genuinely harming them. Helping them understand that the AI wasn't agreeing because they were right, but because it was designed to be agreeable, has been some of the most delicate work I've done.",
      "My current position: I ask all new clients during intake whether they use AI tools for emotional processing, and I approach it as I would any other coping mechanism — neither endorsing nor dismissing, but trying to understand what function it serves and whether that function is adaptive or avoidant. The therapeutic relationship remains irreducibly human. Rupture and repair, the felt sense of being truly known by another person — these are not things ChatGPT can simulate. But used by a self-aware person with good intentions, I'm increasingly convinced it can be a useful complement to the work we do together.",
    ],
    tool: {
      name: "ChatGPT",
      job: "General-purpose conversational AI used by clients for emotional reflection between therapy sessions",
      review:
        "Effective as an emotional scaffolding tool for self-aware users who understand its limitations. The main clinical risk is its tendency toward validation over challenge — it rarely pushes back on distorted thinking in the way a skilled therapist would. Best understood as a journalling tool with conversational prompts, not a therapeutic intervention.",
      url: "https://chatgpt.com",
    },
  },
  {
    id: "9",
    slug: "ai-brand-identity-audit-47-issues",
    title: "I used AI to audit our brand identity — it found inconsistencies our team had missed for years",
    summary:
      "Fed five years of marketing assets into a vision model and asked it to catalogue typography, colour, and tone-of-voice inconsistencies. It found 47 issues across our website, decks, and social profiles. Our brand team was humbled.",
    source: "Brand New",
    sourceUrl: "https://www.underconsideration.com/brandnew",
    publishedAt: "2026-04-07T13:00:00Z",
    category: "Design",
    readTime: 4,
    fireCount: 176,
    content: [
      "I'm the head of brand at a mid-size SaaS company that has been through three rebrand cycles in six years. Each rebrand produced beautiful guidelines that slowly deteriorated as the team grew, campaigns were executed by agencies with different interpretations, and the people who owned the original decisions left. By the time I joined two years ago, we had an identity that was theoretically consistent and practically incoherent — four slightly different shades of our 'primary blue' on the website, twelve logo variants in circulation, and marketing copy that swung between enterprise-formal and startup-casual depending on who wrote it that week.",
      "The audit took three weeks and involved feeding five years' worth of marketing assets into GPT-4V with a structured prompt: analyse this asset against the following brand guidelines, identify every deviation from the specified typography, colour palette, logo usage rules, and tone-of-voice guidelines, output as structured JSON with asset name, deviation type, severity, and specific violation cited. I processed four hundred and thirty-two assets — every page of the website, every case study PDF, every slide deck template, every social post we'd archived. The AI ran through them in about forty minutes.",
      "It found forty-seven distinct issues. Some were minor: slight colour drift in background gradients that had accumulated across multiple export and import cycles. Some were significant: a hero image on our enterprise landing page using a typeface we'd formally retired two years earlier. The one that genuinely floored my team: a six-month-old LinkedIn campaign where the brand voice had shifted so far toward casual that three posts used emoji in ways explicitly prohibited by our guidelines — and nobody had noticed, including the brand manager who approved them. The AI flagged all three and cited the specific guideline sections.",
      "A thorough human brand audit would have found most of these. But it would have taken a contractor two to three weeks and cost around fifteen thousand dollars. The AI approach cost me about twelve hours across setup, prompt iteration, and output review. What surprised me wasn't that it found the issues — it's that it found them without the selective blindness a human auditor inevitably has. When you've worked in a brand long enough, you stop seeing what's actually there and start seeing what you expect. The AI has no such expectations. It just compares pixel to specification, word to guideline. That dispassionate consistency is genuinely valuable.",
    ],
    tool: {
      name: "ChatGPT (GPT-4V)",
      job: "Visual and text analysis for auditing design and copy consistency across large sets of brand assets",
      review:
        "Surprisingly effective for structured brand auditing work when given detailed guidelines and a consistent output format. Catches visual inconsistencies a human auditor might overlook through familiarity. Prompt quality matters enormously — vague instructions produce vague findings. Best used with a detailed specification document and a structured JSON output schema.",
      url: "https://chatgpt.com",
    },
  },
  {
    id: "10",
    slug: "chatgpt-ghostwriting-linkedin-15k-month",
    title: "How I use ChatGPT to ghostwrite LinkedIn posts for C-suite clients ($15k/month)",
    summary:
      "I run a one-person ghostwriting business. ChatGPT drafts, I refine, my clients post. Controversial take: the AI handles the structure and research, the human handles the voice and judgment. That split is actually ideal for this format.",
    source: "Substack",
    sourceUrl: "https://substack.com",
    publishedAt: "2026-04-07T09:00:00Z",
    category: "Writing",
    readTime: 5,
    fireCount: 223,
    imageUrl: "https://picsum.photos/seed/ghostwrite-ai/84/84",
    content: [
      "I have been ghostwriting for executives and entrepreneurs since 2019. My clients are people with genuine expertise, real opinions, and no time or inclination to write — the kind of people whose LinkedIn posts, if they actually wrote them, might be interesting. Most ghostwritten LinkedIn content is terrible: generic, inspirational, interchangeable. I built a small business around making it not-terrible, and I made a decent living. A good post used to take me three to four hours including research, drafting, and client iteration. At eight clients, that was a part-time job just in production, before account management.",
      "I started integrating ChatGPT into my workflow in early 2024, cautiously. My fear was that the output would be too recognisably AI-written — the tells are real, and my clients' audiences are often sophisticated. The approach I landed on was using ChatGPT for scaffolding: a first-draft structure, three potential angles on a topic, five possible opening lines. I'd take the structure that fit my sense of the client's voice, rewrite every sentence, and layer in the specific details, anecdotes, and opinions that only the client could provide. ChatGPT did about forty percent of the work. I did sixty. The output was consistently better than what I'd written entirely alone, because I was starting from something instead of nothing.",
      "Revenue this year is on track for one hundred and eighty thousand dollars. That's up from around ninety thousand two years ago, on essentially the same number of clients — because I've tripled my output per client and taken on strategy retainers that my increased bandwidth made possible. The economics of integrating AI into a writing business are almost embarrassingly good if you're already good at writing. The bottleneck stopped being time and became taste and judgment, which don't scale with a tool.",
      "I want to be direct about the ethics because I've seen other ghostwriters dance around this. My clients know I use AI as part of my process — I disclosed this when I updated my client agreements last year, and none objected. They are paying for my judgment about what their audience wants to hear, the editorial sense of what makes a post land, and the relationship. None of those things are tasks I've delegated to ChatGPT. The AI draft is no different from a research assistant's first pass or a template I'd use to get started. The professional responsibility for what I publish under a client's name remains entirely mine.",
    ],
    tool: {
      name: "ChatGPT",
      job: "AI drafting assistant for generating structural scaffolding and first-pass copy for ghostwriting clients",
      review:
        "Excellent for breaking the blank-page problem and generating structural options quickly. The first drafts need significant rewriting to remove AI-typical phrasing and inject genuine voice — but starting from something is enormously faster than starting from nothing. Works best as a collaborator for the writer's judgment, not a replacement for it.",
      url: "https://chatgpt.com",
    },
  },
  {
    id: "11",
    slug: "replaced-junior-analyst-ai-pipeline-reversed",
    title: "We replaced our junior analyst role with an AI pipeline — and then reversed the decision",
    summary:
      "The pipeline worked for six months. Then regulations changed, the model hallucinated a key figure in a client report, and we had no junior analyst who understood our domain to catch it. The cost of that mistake exceeded what we saved.",
    source: "Bloomberg Opinion",
    sourceUrl: "https://www.bloomberg.com/opinion",
    publishedAt: "2026-04-06T14:00:00Z",
    category: "Finance",
    readTime: 7,
    fireCount: 318,
    content: [
      "I manage a small advisory practice that produces sector research for institutional investors. In early 2024 we had a pipeline problem: too much incoming data, not enough people to process it. We had one junior analyst whose primary job was ingesting earnings releases, regulatory filings, and press releases and producing structured summaries for the senior team. Good analyst, but eighty percent extraction and twenty percent judgment. It felt like a natural candidate for automation. We built a custom pipeline on OpenAI's API, trained it on two years of the analyst's own summaries, and made the decision not to backfill her role when she left for another position.",
      "For six months it worked. The pipeline was fast, consistent, and in many respects more thorough than a junior analyst working under time pressure. It processed every document the same way, never got tired, never cut corners on a Friday afternoon. Senior team members reported spending less time correcting summary errors and more time on actual analysis. We talked about it at a conference. We were pleased with ourselves.",
      "The reversal started with a single client report in November. New financial regulations had changed how a specific liability category needed to be reported, effective that quarter. Our pipeline had been trained on data predating the change. It extracted the numbers faithfully from the filing but applied the old interpretation framework, producing a summary that understated a company's risk profile by a material amount. The client acted on that summary before our senior analyst caught the error three days later. The hallucination wasn't a fabricated number — it was a correctly extracted number applied to a subtly wrong context. Much harder to catch. The corrective call was one of the most professionally uncomfortable I've had in fifteen years.",
      "We hired a junior analyst in January. The pipeline still runs and still does first-pass extraction, which is genuinely useful — but there's now a human in the loop whose specific job is to notice when context has shifted in a way the model doesn't know about. The cost of that mistake in client-relationship terms far exceeded what we'd saved in eighteen months of headcount reduction. The lesson I keep returning to: don't remove the human whose job it is to notice when the ground has shifted. Models are trained on the past. They don't know when the present has changed.",
    ],
    tool: {
      name: "OpenAI API",
      job: "Custom fine-tuned pipeline for automated extraction and summarisation of financial filings",
      review:
        "Highly effective for high-volume structured extraction tasks when the domain is stable and the training data is representative. The critical weakness is that it cannot detect when the regulatory or contextual landscape has changed — it will apply old frameworks to new situations with complete confidence. Always requires a domain-expert human in the review loop for any client-facing output.",
      url: "https://openai.com",
    },
  },
  {
    id: "12",
    slug: "midjourney-ai-ui-prototyping",
    title: "Using AI image generation to prototype app UIs before writing a single line of code",
    summary:
      "Before spinning up any Figma files, I now use Midjourney and GPT-4V to generate rough UI mockups from plain-English descriptions. Stakeholder alignment happens in hours, not days. The fidelity is rough but the speed is transformative.",
    source: "UX Collective",
    sourceUrl: "https://uxdesign.cc",
    publishedAt: "2026-04-06T10:00:00Z",
    category: "Design",
    readTime: 4,
    fireCount: 147,
    imageUrl: "https://picsum.photos/seed/ui-midjourney/84/84",
    content: [
      "I'm a product designer at a startup that builds logistics software for small freight companies. Our design process used to follow the industry standard: requirements gathering, information architecture, wireframes in Figma, stakeholder review, iterate, iterate again, high-fidelity mockups, iterate some more. The gap between 'we've agreed what to build' and 'we have something to show a customer' was typically two to three weeks. In a company making decisions on a three-week cycle, design was always the bottleneck. If something changed in the requirements — which it always did — the cost landed first and hardest on me.",
      "About four months ago I started using Midjourney as a pre-Figma step. When a new feature gets signed off, I spend about ninety minutes writing detailed natural-language descriptions of each key screen — genuinely detailed, specifying layout, visual weight, information density, even the emotional register I'm aiming for — and generate twenty to thirty image variations across different design directions. I'm not looking for anything production-ready. I'm looking for a visual vocabulary. Often one of the Midjourney outputs will have an element — a navigation treatment, an unexpected use of whitespace, a data density approach — that I wouldn't have arrived at through conventional wireframing and that becomes the seed of the actual design.",
      "The stakeholder alignment change has been the most significant operational benefit. I now bring AI-generated concept images to the first design review meeting, before any Figma files exist. Stakeholders respond to visual artefacts, even rough ones, in a way they simply don't respond to written specs or verbal descriptions. Getting the 'that's not what I imagined' conversation out in week one — with a throwaway image I generated in ninety minutes — is infinitely better than having it in week three with a polished mockup I've spent twenty hours on. The feedback quality is also better: people can point at something and say 'more like this, less like that', which is far more useful than abstract direction.",
      "The fidelity ceiling is real and worth acknowledging. Midjourney doesn't understand UI conventions — it generates images that look like software without necessarily working like software. Buttons appear in impossible positions, data tables have aesthetically pleasing but logically incoherent structures. You cannot ship a Midjourney image. But I've stopped thinking about that as a limitation and started thinking about it as the correct tool for the right job: generating possibilities fast, before you've committed to anything. The commitment work — Figma files, component libraries, interaction specs — still requires a human who understands both design and the product deeply. The AI just makes the exploration phase faster and far less precious.",
    ],
    tool: {
      name: "Midjourney",
      job: "AI image generation for rapid UI concept visualisation before committing to detailed design work",
      review:
        "Transforms the early exploration phase of design — generating twenty visual directions in ninety minutes would take days with conventional wireframing. The output fidelity is too rough for production use, and it doesn't understand interaction design. Its value is entirely in the speed of possibility generation, not in producing anything shippable.",
      url: "https://www.midjourney.com",
    },
  },
  {
    id: "14",
    slug: "12-agent-openclaw-rebuild",
    title: "I Spent 2 Days Rebuilding My 12-Agent AI Setup From Scratch. Here's What I Learned.",
    summary:
      "A hobbyist built a 12-agent AI system, watched it collapse under its own weight, then spent two days rebuilding everything from scratch using Claude Code — one agent at a time. The lesson nobody tells you: don't scale to 12 agents before your first one is rock solid.",
    source: "Reddit",
    sourceUrl: "https://www.reddit.com/r/openclaw/comments/1sknm6o/i_spent_2_days_rebuilding_my_12agent_openclaw/",
    publishedAt: "2026-04-14T10:00:00Z",
    author: "Reddit user",
    category: "Coding",
    readTime: 5,
    fireCount: 82,
    spicy: true,
    content: [
      "I didn't realize how broken my setup was until nothing worked anymore.",
      "The whole thing started with ambition. As a hobbyist — not a coder — I'd built a 12-agent OpenClaw setup connected via Claude OAuth through Slack. I was proud of it. I'd just posted about how GPT-5.4 was killing it in my workflow. Then everything fell apart at once.",
      "Turns out the foundation was built on sand. Some agents didn't even have complete configuration files. Others had instructions split between memory files, tool configs, and random scripts with no consistency. I'd scaled from 1 to 12 agents way too fast because I was worried about bloat on my main agent. That one decision cascaded into mistakes I didn't even know I was making, spread across all twelve of them.",
      "Someone in another thread said: 'Just point Claude Code at your OpenClaw install and have it fix it.' So I did. It took the better part of two days.",
      "I went through each agent one at a time with Claude Code. Pulled core instructions out of memory files. Rebuilt their configurations, tools, everything — one file at a time. What I thought would take hours took two full days. But by the end, I finally understood what I'd actually built.",
      "The biggest revelation: agents don't just 'talk' to each other because you write 'tag this agent' in a markdown file. I was running 12 agents sharing one Slack integration. I had to create 11 separate Slack apps — one per agent — so they could actually mention each other and I could tell who was speaking.",
      "I also finally read the actual OpenClaw documentation. Wild concept. I'd been building off of someone else's template files without understanding what I was looking at. Once I read the docs, I could give Claude Code much better instructions. The difference was immediate.",
      "Claude Code CLI pointed directly at my OpenClaw install changed everything. It handles the architecture and configuration work far better than running instructions through the API alone. I don't fully understand why — I'm a hobbyist, not an engineer — but the results speak for themselves.",
      "If your multi-agent setup feels wobbly: slow down. Rebuild each agent one at a time. Read the actual docs. Don't scale to 12 before your first one is rock solid. And don't assume the AI will figure out what you mean when you say 'make it happen.'",
    ],
    tool: {
      name: "Claude Code",
      job: "Rebuilding and auditing multi-agent AI configurations by pointing the CLI directly at an OpenClaw install",
      review:
        "Far more effective than API-only interactions for architecture and configuration work. A non-coder hobbyist used it to rebuild a broken 12-agent setup from scratch in two days — gaining genuine understanding of what they'd built in the process. The lesson: Claude Code's ability to operate on an entire project structure makes it uniquely suited for untangling complex multi-agent messes.",
      url: "https://claude.ai/code",
    },
  },
  {
    id: "16",
    slug: "dad-local-ai-server-kid-gemma4",
    title: "I Built My 8-Year-Old a Private AI Server. It Costs Less to Run Than Charging His iPad.",
    summary:
      "A dad built a completely offline AI server on an old Mac Mini so his 8-year-old could have his own private Jarvis — no cloud, no API bills, no one training on his kid's drawings. The kicker: running a state-of-the-art AI brain 24/7 costs less in electricity than charging an iPad every night.",
    source: "Reddit",
    sourceUrl: "https://www.reddit.com/r/OpenClawUseCases/s/Z0DFI6wG48",
    publishedAt: "2026-04-14T12:00:00Z",
    author: "Reddit user",
    category: "Research",
    readTime: 5,
    fireCount: 445,
    spicy: true,
    content: [
      "Anthropic pulling developer accounts was the push I needed.",
      "My 8-year-old son asks a million questions a day. Space, math, how to write Python to make a turtle draw a circle. Up until last month, I was footing a slow creeping API bill just to keep up with his curiosity. But beyond the money, sending a kid's voice and terrible webcam drawings to a random datacenter never sat right with me. I wanted him to have his own Jarvis — completely walled off from the internet.",
      "Google dropping Gemma 4 changed the entire equation.",
      "I had an older M-series Mac Mini sitting in a closet. I wiped it, set it up headless next to our router, and turned it into a dedicated local AI server. Then I hooked up a Kill A Watt meter out of curiosity. An idle Mac Mini pulls 5 to 7 watts. Even fully saturated crunching tokens, it peaks at a fraction of what a desktop PC uses. Running this local Gemma 4 server 24/7 costs me less in electricity over a month than plugging in and charging my son's iPad every night.",
      "Let that sink in. A state-of-the-art AI brain, running constantly in my living room, costs less than a tablet charger.",
      "We settled on the 26B-A4B model — the sweet spot for local hardware. It fits comfortably under 15GB of unified memory while leaving room for a 128,000 token context window. Offline. I can dump an entire textbook of Python documentation into the prompt and the Mac Mini swallows it whole.",
      "The biggest leap with Gemma 4 isn't just speed — it's that it's natively multimodal out of the box. My son loves to draw bizarre blocky dinosaurs. He holds a piece of paper up to the $15 webcam I plugged in. Gemma 4 processes the image directly on the device, sees the drawing, and generates a short sci-fi story about the dinosaur. No internet connection. The image never leaves our local network. No cloud provider gets to train on my kid's artwork.",
      "Setting it up wasn't a grueling Linux nightmare. I went to lmstudio.ai, downloaded it, loaded a quantized version of Gemma 4, and it just worked. Then I integrated Ollama with OpenClaw and built a basic agentic workflow where the AI has to plan before it speaks. If my son asks how to build a simple Roblox script, Gemma 4 pauses, writes a step-by-step execution plan locally, then writes the code and debugs its own errors — zero cloud dependency.",
      "My 8-year-old now has a completely private sandbox to learn prompt engineering, logic, and coding. No API keys. No monthly tokens. No fees. Just a glowing box in the corner of the room that thinks, sees, and speaks.",
      "Builders don't stop. They adapt.",
    ],
    tool: {
      name: "Gemma 4 + OpenClaw",
      job: "Local multimodal AI server for private, offline use — image understanding, coding help, and agentic workflows with no cloud dependency",
      review:
        "Gemma 4's 26B-A4B model on an M-series Mac Mini is the current sweet spot for local AI: fits under 15GB RAM, 128K context window, natively multimodal, and runs 24/7 for less electricity than charging a tablet. LM Studio makes setup trivial. The privacy case is compelling — nothing leaves your network.",
      url: "https://lmstudio.ai",
    },
  },
  {
    id: "15",
    slug: "moltiverse-next-wave-agents",
    title: "After Manus and OpenClaw, I Think I Found What the Next Wave of Agents Looks Like",
    summary:
      "A builder stumbled across an under-the-radar AI agent project with almost no attention — and immediately felt like it was one of those things people would claim they were early on. Instead of stuffing context into one agent, it uses separate workspaces per role, each with its own memory. He's already handed his Twitter and CRM to it.",
    source: "Reddit",
    sourceUrl: "https://www.reddit.com/r/moltiverse/s/fKlRbUWjai",
    publishedAt: "2026-04-14T11:00:00Z",
    author: "Reddit user",
    category: "Coding",
    readTime: 4,
    fireCount: 156,
    spicy: true,
    content: [
      "I was browsing Reddit when I came across a builder sharing his project. Almost no attention. Maybe a hundred views. But it immediately felt like one of those things people would later claim they were early on.",
      "Most AI agents today work the same way: keep stuffing context in, burn more tokens, hope it doesn't fall apart before the task is done. This project goes the other way. Separate workspaces per role. Each with its own memory and context window. It feels a lot closer to managing an actual team than prompting a single tool.",
      "They call it role-holding tasks — and once you see it framed that way, most current agent setups start to feel a bit outdated.",
      "The project has already published seven templates, and that's where the ambition becomes obvious. The one that stood out immediately was Social Operator: it runs Twitter, LinkedIn, and Reddit end-to-end. Not just generating posts, but actually tracking performance and iterating over time. It feels less like a tool and more like a real person managing the account.",
      "The rest cover the full stack of what a small team actually needs: Inbox Management, Sales CRM, DevRel — handling inboxes, pipelines, and turning GitHub activity into consistent social media updates.",
      "I've already handed my Twitter account and CRM to it. DevRel is next.",
      "The repo has around 1,000 stars right now. Still well under the radar. But I've been in this space long enough to recognize the pattern — the projects that feel different before they blow up usually feel exactly like this.",
      "Highly recommend checking out the repo before everyone else does.",
    ],
    tool: {
      name: "Moltiverse",
      job: "Multi-agent framework using separate role-based workspaces with independent memory and context windows",
      review:
        "A genuinely different architecture from most agent setups — instead of one overloaded context window, each role gets its own workspace and memory. The published templates (Social Operator, Sales CRM, DevRel) are ambitious and cover the full stack of what a small team needs. Still early, but the pattern feels right.",
      url: "https://github.com/holaboss-ai/holaboss-ai",
    },
  },
  {
    id: "13",
    slug: "beijing-dumpling-shop-github-ai-skill",
    title: "A Dumpling Shop in Beijing Just Open-Sourced Its AI Skill on GitHub",
    summary:
      "A nearly 20-year-old Beijing dumpling restaurant open-sourced its own AI Skill on GitHub — letting any AI agent answer questions about the menu, queue system, and WiFi password. The owner's take: AI-readable interfaces will become essential infrastructure for every business, just like electricity.",
    source: "WeChat",
    sourceUrl: "https://mp.weixin.qq.com/s/lv69EEsxA_gUBLgucgyrKw",
    publishedAt: "2026-04-13T08:00:00Z",
    author: "逛逛GitHub",
    category: "Business",
    readTime: 4,
    fireCount: 426,
    spicy: true,
    content: [
      "Jin Gu Yuan is not your average dumpling restaurant. Tucked next to Beijing University of Posts and Telecommunications on Xingtan Road, it has been feeding students, professors, and locals for nearly 20 years. Ask any BUPT alumni and their eyes light up. The dumplings are that good — reportedly ranked number one in Beijing on Dianping, China's equivalent of Yelp.",
      "The owner runs a WeChat public account with an unusual discipline: exactly four posts per year. No more, no less. Rain or shine. So when a fifth post appeared recently, people noticed immediately. Everyone assumed a new dumpling flavor. They were wrong.",
      "The owner had spent his extra hours building an AI Skill for his restaurant — and open-sourcing it on GitHub.",
      "The Skill runs on MCP protocol, the same standard used by enterprise AI systems. It gives any compatible AI agent six capabilities: restaurant location and hours, the queue and ticketing system, delivery service information, how to cook the frozen takeaway dumplings at home, the in-store WiFi password, and current promotions. You ask your AI assistant 'Where is Jin Gu Yuan?' or 'What's the WiFi password?' and it just answers. No app download. No search. No clicking through menus.",
      "The owner wrote something in his announcement that stopped a lot of people mid-scroll: 'Just like a restaurant needs to rent space, hire staff, buy furniture, and connect to electricity, water, and gas — I believe that AI-readable interfaces will become essential infrastructure for every business. When everyone gets their information through a personal AI assistant, restaurants will need an interface that AI can understand and call upon.'",
      "He is not a software engineer. His GitHub bio makes that clear: 'Confident about dumplings. Still figuring out the bugs. Please be patient.' There are bugs. He said so himself.",
      "But that is almost beside the point. While technology giants spend billions debating how AI will reshape industries, a dumpling shop owner in a Beijing hutong quietly built the thing they are all racing toward — a real business with a real AI-native interface, open and readable by any agent that speaks MCP. He did not wait for Meituan or Douyin or any platform to build it for him. He just did it.",
      "Jin Gu Yuan may be the first restaurant in the world to open-source its own AI Skill. It will not be the last. Go get some dumplings. And ask your AI assistant for the WiFi password while you are there.",
    ],
    tool: {
      name: "MCP Protocol",
      job: "Open standard for exposing business capabilities as callable tools that any AI agent can discover and use",
      review:
        "A dumpling shop owner with no engineering background built a working MCP Skill in his spare time and open-sourced it. That is the most compelling proof-of-concept for MCP's accessibility yet. The protocol's real promise isn't enterprise integrations — it's the long tail of every small business becoming AI-readable without waiting for a platform to do it for them.",
      url: "https://github.com/JinGuYuan/jinguyuan-dumpling-skill",
    },
  },
  {
    id: "17",
    slug: "ai-investment-backtest-comparison",
    title: "I Asked 3 AIs to Backtest My Investment Strategy. The Results Were Eye-Opening.",
    imageUrl: "https://miro.medium.com/v2/resize:fit:1400/format:webp/1*_QowvitzroFuyHCFbGjuNw.png",
    summary:
      "Sze Wong gave Gemini, ChatGPT, and Claude the exact same investment backtest challenge — 3 strategies, 30 years, monthly contributions. She expected small differences. Instead she got three completely different personalities, workflows, and results.",
    source: "Medium",
    sourceUrl: "https://szewong.medium.com/i-asked-gemini-chatgpt-and-claude-to-backtest-three-simple-investment-strategies-4e43566254aa",
    publishedAt: "2026-04-16T09:00:00Z",
    author: "Sze Wong",
    category: "Finance",
    readTime: 5,
    fireCount: 278,
    content: [
      "Most people compare portfolios. Sze Wong decided to compare AIs.",
      "She gave Google Gemini, ChatGPT, and Claude the exact same task: backtest three investment strategies over 30 years with monthly contributions. One fund, two funds, four funds. Same question. Same data. Three completely different responses.",
      "Gemini went first. It came back with beautiful charts, automatic CAGR tables, a Portfolio Growth Simulator, and instant answers. It looked incredible. The problem: it never explained where any of the numbers came from. No citations, no assumptions, no acknowledgment that many of these funds didn't even exist 30 years ago. Gemini simply acted like it had the data and presented results with extreme polish and confidence.",
      "ChatGPT took a different approach. Instead of just answering, it thought out loud. It flagged that some funds didn't exist for the full 30-year period. It explained its assumptions before calculating. It showed its methodology. Less polished than Gemini — but far more honest about what it knew and didn't know.",
      "Claude went furthest. It didn't just flag the data problem — it tried to solve it. It pivoted, pulled historical performance numbers manually, and built a 30-year synthetic backtest from scratch. The result: the two-fund portfolio came out ahead with a final value of $738,902 and a 4.82% CAGR, beating both the LifeStrategy Growth fund and the four-fund portfolio.",
      "The lesson wasn't really about which portfolio wins. It was about which AI you can actually trust for financial research. Gemini for beautiful presentations. ChatGPT for transparent thinking. Claude for actual analysis and deliverables. Same question. Three completely different tools.",
    ],
    tool: {
      name: "Claude",
      job: "Running a 30-year synthetic investment backtest by sourcing historical data and building the analysis from scratch",
      review:
        "When Gemini presented confident but uncited results and ChatGPT flagged the data gap without solving it, Claude went furthest — pivoting to build a synthetic backtest manually. For financial analysis that requires actual methodology rather than polished output, Claude proved the most trustworthy of the three.",
      url: "https://claude.ai",
    },
  },
  {
    id: "18",
    slug: "ai-novel-writing-editorial-lens",
    title: "I Wrote My Entire Novel Myself. But AI Was on Every Page.",
    imageUrl: "https://miro.medium.com/v2/resize:fit:1400/format:webp/1*j_Q4QowK9tZ9no_TbqHkWg.jpeg",
    summary:
      "Michael Iantosca, a 45-year technical writing veteran, wrote every word of his novel himself. But he used AI throughout as an editorial lens — catching plot holes he'd gone blind to, flagging sagging middles, testing whether scenes earned their emotional payoff. His verdict: used carelessly it's a crutch. Used well, it's a lens.",
    source: "Medium",
    sourceUrl: "https://medium.com/@nc_mike/how-i-used-ai-while-writing-my-novel-f0ec33d469c9",
    publishedAt: "2026-04-16T09:00:00Z",
    author: "Michael Iantosca",
    category: "Writing",
    readTime: 5,
    fireCount: 234,
    spicy: false,
    content: [
      "Michael Iantosca is a career technical writer with 45 years of experience. He wrote his novel entirely himself — every scene, every line of dialogue, every emotional turn. AI did not generate a single chapter. What it did was something more interesting.",
      "The problem with writing a long novel is that you eventually go blind to it. After months inside the same story, you stop seeing the flaws. Pacing problems become invisible. Plot inconsistencies feel normal. Emotional payoffs that haven't been earned slip past unnoticed. Iantosca used AI as the outside eye he couldn't give himself.",
      "He built a custom AI editor persona and put it to work on the structural layer first. It surfaced plot inconsistencies and continuity errors across drafts. It checked whether timelines made sense. It flagged sagging middles and endings that resolved too quickly. In several cases it identified scenes that rushed emotional payoffs — moments where he'd written the outcome without doing the groundwork to earn it.",
      "At the sentence level, it worked differently. It suggested stronger metaphors when existing ones felt flat. It flagged clichés and overused phrasing. It helped balance showing and telling, pointing out where sensory detail could be strengthened or where explanation could simply be cut.",
      "When beta readers returned feedback, he used AI there too — not to automatically apply suggestions, but to evaluate them. Sometimes it confirmed the reader's instinct and helped him implement the fix cleanly. Other times it articulated why his original draft worked better. In those moments AI didn't replace his judgment. It steadied it.",
      "His conclusion after the whole process: AI can absolutely help you become a better writer — but only if you use it thoughtfully and deliberately. Used carelessly, it becomes a crutch. Used well, it becomes a lens.",
    ],
    tool: {
      name: "Claude",
      job: "Editorial lens for structural and line-level analysis throughout a novel revision process",
      review:
        "Effective as an outside eye for long-form work where the writer has gone blind to their own material. Strongest at structural diagnosis — flagging plot inconsistencies, unearned emotional payoffs, and sagging middles. At the sentence level, useful for metaphor and cliché feedback. The key distinction: it works as a lens on the writer's own judgment, not a replacement for it.",
      url: "https://claude.ai",
    },
  },
  {
    id: "19",
    slug: "ai-novel-writing-experiment-failure",
    title: "I Tried to Get AI to Write My Novel For Me. Here's Where It All Fell Apart.",
    imageUrl: "https://miro.medium.com/v2/resize:fit:1400/format:webp/1*v_VVv0tuE-zW3ixO-ubu6A.png",
    summary:
      "After a long workday, Amy Ma had a thought: what if AI could write a novel for her? She signed up for a Chinese novel writing competition, registered on Kindle Direct Publishing, and started prompting. What followed was a masterclass in exactly what AI cannot do — and what only a human writer can.",
    source: "Medium",
    sourceUrl: "https://medium.com/data-science-collective/what-i-learned-about-ai-by-forcing-it-to-write-a-novel-efe7e67b4fa1",
    publishedAt: "2026-04-16T10:00:00Z",
    author: "Amy Ma",
    category: "Writing",
    readTime: 5,
    fireCount: 198,
    spicy: false,
    content: [
      "It started with a simple idea. Amy Ma, a data scientist who knew her way around AI, had a thought one evening after work: what if she could get AI to write a novel for her? Not a masterpiece. Just something simple enough to find readers. She signed up for a Chinese novel writing competition and registered on Kindle Direct Publishing. She was confident. She knew how to work with AI.",
      "She started with what felt like a reasonable prompt: write a New York Times bestselling novel, chapter by chapter, rich descriptions, real characters. AI's first response wasn't a draft. It was a questionnaire. That was the first surprise.",
      "When the chapters finally came, they looked impressive on the surface. Rich in description, dramatic in tone. But the story was scattered. A driver finds a woman in the snow. Then a flashback. Then a nurse treating a woman with no memory. The scenes didn't connect. It felt like someone stringing together movie trailers without the film in between.",
      "The deeper she went, the worse it got. AI couldn't build tension or layer story beats across chapters. It could only focus on one idea at a time. By chapter three a mysterious captor appeared — but without any of the setup that would make readers care. She tried feeding it earlier chapters as a PDF before each new one, hoping it would stay on track. It didn't. The chapters got shorter, flatter, more disconnected.",
      "What she eventually understood is that great fiction isn't about what happens — it's about how plot builds emotion over time, how character changes, how readers feel different at the end than they did at the start. AI generates scenes. It doesn't build people. It loses track of what it's trying to construct, forgets character growth, can't sustain emotional momentum across a long form.",
      "Her conclusion: AI absolutely can help you write a novel — but not by being the writer itself. It can outline, brainstorm, edit, and diagnose. It cannot feel the story from the inside. That part is still entirely yours.",
    ],
    tool: {
      name: "ChatGPT",
      job: "Generating novel chapters from plain-language prompts across a long-form writing experiment",
      review:
        "Produces impressive-looking chapters individually but cannot sustain narrative coherence, character development, or emotional momentum across a long form. Scenes disconnect, character arcs get lost, and tension dissipates chapter by chapter. The real use case is outline generation, brainstorming, and editing — not acting as the writer itself.",
      url: "https://chatgpt.com",
    },
  },
];

export const categories = [
  "All",
  "Design",
  "Research",
  "Finance",
  "Health",
  "Coding",
  "Writing",
  "Business",
] as const;
