import { Story } from "@/types/story";

export const mockStories: Story[] = [
  {
    id: "1",
    title: "How I redesigned our entire onboarding flow in a weekend using Figma AI",
    summary:
      "As a solo designer at a 12-person startup, I used Figma's AI features to generate component variants, auto-layout suggestions, and copy alternatives. What used to take two sprints took two days. Here's my exact workflow.",
    source: "Maya R. on Medium",
    sourceUrl: "#",
    publishedAt: "2026-04-11T10:00:00Z",
    category: "Design",
    readTime: 6,
    fireCount: 382,
    imageUrl: "https://picsum.photos/seed/figma-ai/84/84",
  },
  {
    id: "2",
    title: "I'm a nurse. I've been using Claude to explain diagnoses to patients — here's what happened",
    summary:
      "My patients often leave consultations confused by medical jargon. I started using Claude on my tablet to rephrase doctor's notes into plain English on the spot. Patient comprehension scores on our ward went up 40% in six weeks.",
    source: "r/nursing",
    sourceUrl: "#",
    publishedAt: "2026-04-11T08:30:00Z",
    category: "Health",
    readTime: 5,
    fireCount: 341,
    imageUrl: "https://picsum.photos/seed/nurse-claude/84/84",
  },
  {
    id: "3",
    title: "Using Perplexity instead of Google for every research paper — a student's honest review",
    summary:
      "I'm a PhD student in materials science. I switched my entire literature review process to Perplexity AI three months ago. It cites sources, handles follow-up questions, and surfaces papers I'd never have found on Google Scholar. But it's not perfect.",
    source: "Hacker News",
    sourceUrl: "#",
    publishedAt: "2026-04-10T14:00:00Z",
    category: "Research",
    readTime: 7,
    fireCount: 297,
    imageUrl: "https://picsum.photos/seed/perplexity-research/84/84",
  },
  {
    id: "4",
    title: "I let GitHub Copilot write 80% of my last feature — code review was a nightmare",
    summary:
      "Copilot is genuinely impressive for boilerplate and CRUD operations. But when I shipped a feature that was 80% AI-generated without deeply reviewing it, I introduced three subtle bugs that only showed in production. Lessons learned the hard way.",
    source: "Dev.to",
    sourceUrl: "#",
    publishedAt: "2026-04-10T11:00:00Z",
    category: "Coding",
    readTime: 8,
    fireCount: 271,
  },
  {
    id: "5",
    title: "Our hedge fund built a custom GPT-4 pipeline to summarise earnings calls — ROI in 3 months",
    summary:
      "We process 200+ earnings call transcripts per quarter. After training a fine-tuned summarisation pipeline on historical calls, our analysts spend 70% less time on transcripts and more time on actual thesis development. Full technical breakdown inside.",
    source: "Fintech Insider",
    sourceUrl: "#",
    publishedAt: "2026-04-09T16:00:00Z",
    category: "Finance",
    readTime: 9,
    fireCount: 258,
    imageUrl: "https://picsum.photos/seed/finance-gpt/84/84",
  },
  {
    id: "6",
    title: "Claude helped me write a novel in 90 days. I have complicated feelings about it.",
    summary:
      "I used Claude as a co-writer for my debut thriller — brainstorming plot holes, writing dialogue drafts, and pushing through blocks. The book is done and my agent loves it. But I'm still wrestling with what authorship means now.",
    source: "Electric Lit",
    sourceUrl: "#",
    publishedAt: "2026-04-09T09:00:00Z",
    category: "Writing",
    readTime: 10,
    fireCount: 389,
    imageUrl: "https://picsum.photos/seed/novel-claude/84/84",
  },
  {
    id: "7",
    title: "Cursor + Claude: how I went from junior to shipping features solo",
    summary:
      "Six months ago I was stuck needing senior review for every PR. Using Cursor with Claude as an always-on mentor, I can now ship complete features, write tests, and debug production issues independently. This is what pair programming should have always been.",
    source: "Personal blog",
    sourceUrl: "#",
    publishedAt: "2026-04-08T12:00:00Z",
    category: "Coding",
    readTime: 5,
    fireCount: 312,
  },
  {
    id: "8",
    title: "A therapist's take on patients who use ChatGPT between sessions",
    summary:
      "More of my clients are showing up having already processed emotions with ChatGPT before our sessions. Some arrive more self-aware; others have reinforced unhelpful patterns. As a therapist, I'm learning to work with AI — not against it.",
    source: "Psychology Today",
    sourceUrl: "#",
    publishedAt: "2026-04-08T07:00:00Z",
    category: "Health",
    readTime: 6,
    fireCount: 204,
    imageUrl: "https://picsum.photos/seed/therapist-chatgpt/84/84",
  },
  {
    id: "9",
    title: "I used AI to audit our brand identity — it found inconsistencies our team had missed for years",
    summary:
      "Fed five years of marketing assets into a vision model and asked it to catalogue typography, colour, and tone-of-voice inconsistencies. It found 47 issues across our website, decks, and social profiles. Our brand team was humbled.",
    source: "Brand New",
    sourceUrl: "#",
    publishedAt: "2026-04-07T13:00:00Z",
    category: "Design",
    readTime: 4,
    fireCount: 176,
  },
  {
    id: "10",
    title: "How I use ChatGPT to ghostwrite LinkedIn posts for C-suite clients ($15k/month)",
    summary:
      "I run a one-person ghostwriting business. ChatGPT drafts, I refine, my clients post. Controversial take: the AI handles the structure and research, the human handles the voice and judgment. That split is actually ideal for this format.",
    source: "Substack",
    sourceUrl: "#",
    publishedAt: "2026-04-07T09:00:00Z",
    category: "Writing",
    readTime: 5,
    fireCount: 223,
    imageUrl: "https://picsum.photos/seed/ghostwrite-ai/84/84",
  },
  {
    id: "11",
    title: "We replaced our junior analyst role with an AI pipeline — and then reversed the decision",
    summary:
      "The pipeline worked for six months. Then regulations changed, the model hallucinated a key figure in a client report, and we had no junior analyst who understood our domain to catch it. The cost of that mistake exceeded what we saved.",
    source: "Bloomberg Opinion",
    sourceUrl: "#",
    publishedAt: "2026-04-06T14:00:00Z",
    category: "Finance",
    readTime: 7,
    fireCount: 318,
  },
  {
    id: "12",
    title: "Using AI image generation to prototype app UIs before writing a single line of code",
    summary:
      "Before spinning up any Figma files, I now use Midjourney and GPT-4V to generate rough UI mockups from plain-English descriptions. Stakeholder alignment happens in hours, not days. The fidelity is rough but the speed is transformative.",
    source: "UX Collective",
    sourceUrl: "#",
    publishedAt: "2026-04-06T10:00:00Z",
    category: "Design",
    readTime: 4,
    fireCount: 147,
    imageUrl: "https://picsum.photos/seed/ui-midjourney/84/84",
  },
];

export const categories = [
  "All",
  "Design",
  "Research",
  "Finance",
  "Health",
  "Coding",
  "Writing",
] as const;
